### ISSUE TITLE
includePrescriptionIssues not included

### ISSUE THREAD

**Issue by no-man-is-an-island** [nhsconnect/integration-adaptor-gp2gp#137]
Affects version: 0.0.4

Error: As per spec at https://developer.nhs.uk/apis/gpconnect-1-2-3/accessrecord_structured_development_retrieve_patient_record.html, `includePrescriptionIssues` parameter is mandatory is mandatory if `includeMedication` is set. Currently the parameter set is:

```
{"resourceType":"Parameters","parameter":[{"name":"patientNHSNumber","valueIdentifier":{"system":"https://fhir.nhs.uk/Id/nhs-number","value":"9690938622"}},{"name":"includeAllergies","part":[{"name":"includeResolvedAllergies","valueBoolean":true}]},{"name":"includeMedication"},{"name":"includeConsultations","part":[{"name":"includeNumberOfMostRecent","valueInteger":3}]},{"name":"includeProblems"},{"name":"includeImmunisations"},{"name":"includeUncategorisedData"},{"name":"includeInvestigations"},{"name":"includeReferrals"}]}
```

**Comment by mattd-kainos** [comment]
GP Connect spec: includePrescriptionIssues is optional, default true
GP Connect test pack: includePrescriptionIssues is mandatory

@no-man-is-an-island will follow up with the GP Connect team to find out which is correct
